conda install -y -c anaconda pandas
conda install -y -c anaconda numpy
conda install -y -c conda-forge holidays
conda install -y -c conda-forge matplotlib
conda install -y -c anaconda seaborn
conda install -y -c conda-forge ddt
conda install -y -c anaconda unittest2
conda install -y -c anaconda configparser
conda install -y -c anaconda cryptography
conda install -y -c anaconda statsmodels
conda install -y -c anaconda scikit-learn
conda install -y -c quantopian trading-calendars